### ISSUE TITLE
Multiple USB devices configuration

### ISSUE THREAD

**Issue by xshi** [psi46/elComandante#1]
Hello Experts, 

I'm trying to use the elComandante on Ubuntu Linux with three USB devices: 

DTB, Keithely2410(USB converter), and JUMO coldbox.  Unfortunately, every time I plugin the coldBox, the system can't recognize it (I guess it's due to the conflict with other FTDI chips).  I noticed  in the config/elComandante.conf.default file: 

port: /dev/ttyJUMO

I'm wondering if you have some suggestions to get them all set up.  In my case the Jumo is shown in the /dev/ttyUSB0, with the command

$ udevadm info -a -n /dev/ttyUSB0 | grep '{serial}' | head -n1
I found the serial number: ATTRS{serial}=="0000:00:14.0"  
But even if I put the usb rules as: 
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", ATTRS{serial}=="0000:00:14.0", SYMLINK+="ttyUSB.jumo" 
It doesn't work. 

Please let me know. 

Thank you!
Xni

**Comment by veloxid** [comment]
Hi Xni,
Just for your information: 
We are using keithleys connected to an internal serial port, as well as keithleys connected with a usb-to-serial-converter, we do not have any problems
We are using a RHEL machine and created udev rules for the different devices in the folder /etc/udev/rules.d/
For JUMO - 12-jumo.rules:
SUBSYSTEM == "tty", ATTRS{manufacturer} == "FTDI", ATTRS{product} == "USB <-> Serial", SYMLINK = "ttyJUMO", GROUP = "usb", MODE = "0664"
SUBSYSTEM == "usb", ATTRS{manufacturer} == "FTDI", ATTRS{product} == "USB <-> Serial", GROUP = "usb", MODE = "0664"

For dig testboards - 09-digTestboard.rules: 
SUBSYSTEM == "usb", ATTR{product} == "DTB v1.2", GROUP="usb", MODE="0664"

For analog testboards: 10-testboards.rules:
SUBSYSTEM == "usb", ATTR{product} == "DLP-USB245M", GROUP="usb", MODE="0664"
SUBSYSTEM == "usb", ATTR{idVendor} == "0403", ATTR{idProduct} == "6014", GROUP="usb", MODE="0664"

If you still have the problem, could you please explain a bit more in detail what doesn't work?
Cheers
Felix

**Comment by xshi** [comment]
Hi Felix, 

Thanks for your instructions. I have added the rules and they can be recognized by the system (Ubuntu)  correctly. However, the only problem so far is that: after a fresh reboot of the the PC, the jumo is not able to be connected by the "coolingBoxClient.py" unless I ran the pXar at the same time. I guess there might be some conflict in the USB interface scan inside pXar: 

core/usb/USBInterface.libftdi.cc:  status =  ftdi_usb_find_all(&ftdic, devlist,vendorID,productID_FT232H);

I'll check with the latest pXar and see if I will repeat the similar symptom. 

Best,
Xin

**Comment by xshi** [comment]
It's solved. Thanks!
Xin

**Comment by veloxid** [comment]
Hi Xin, Could you please explain what solved your problem?
Felix

**Comment by xshi** [comment]
Hi Felix, 

Instead of using the individual coolingBoxClient.py, I used the central el_comandante.py, it's much smoother and never found the non-connection issue. So, I regard it as solved. 

Thanks.
Xin
