### ISSUE TITLE
Settings of coldbox

### ISSUE THREAD

**Issue by veloxid** [psi46/elComandante#2]
Hi Felix,

Here is CERN site.
As we know the test in cold box should be at 17 and -20 degree[1].
However, do you know what the reason the temperature set in 17?
Is the reason of the temperature of chiller?
How much the temperature of chiller in ETH now?

And another question about the procedure which weren’t written in twiki[1].
Should we test 4 measurement ( 2 before/after thermal cycling)? As like following? 
Fulltest@17, IV@17, Fulltest@-20, IV@-20, Cycle(17 and -25), Fulltest@17, IV@17, Fulltest@-20, IV@-20 

Many thanks,
Jui-Fa

[1] https://twiki.cern.ch/twiki/bin/viewauth/CMS/BPixSpecs

**Comment by veloxid** [comment]
Hi Jui-Fa,

It was decided to test at 17degC because of the water at PSI which has a temperature of 17-19degC. This temperature was already used in the past for the production of the analog Modules, and it was decided to stay at this temperature.
At ETH we have a water temperature between 15-17 degC. We are not using a chiller.

A Full-Qualification consist out of the following steps:
Fulltest@-20, Cycle(17 and -20/-25), Fulltest@-20,IV@-20,Fulltest@17,IV@17

IO am not 100% sure wether the test temperature is -20 or -25degC.
I hope that Andrey will answer this.

I am not sure on which temperature we agreed on for cycling.
I ll update the twiki of elcomandante as well:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/ElComandante

Cheers
Felix

**Comment by alphatsai** [comment]
Hi Felix,

Yesterday, Andrey was at CERN and in our cold box lab.
His answer is 
Fulltest@-20, Cycle(17 and -25), Fulltest@-20,IV@-20,Fulltest@17,IV@17

Thanks,
Jui-Fa

**Comment by veloxid** [comment]
Yes that's right is is exactly the procedure Jui-Fa described.
