### ISSUE TITLE
Data transfer to local storage

### ISSUE THREAD

**Issue by xshi** [psi46/elComandante#3]
Hello Experts, 

Are there any way to store the testing data (including the log files) to a local storage, simply another folder?   I have tried to supply the storageDir: /home/user/storage/dir

and add the [Transfer]
destination: /home/user/storage/dir

It does not work. At the end of the el_comandante.py session, all the logfiles are removed. 

Any suggestions? 

Thanks!

Xin

**Comment by alphatsai** [comment]
Hi Xin,

In my case, it always works when I set the storage path in "dataDir:<!Directories|baseDir!>" in elComandante.conf

Hopefully, it's your question.

Cheers,
Jui-Fa

**Comment by xshi** [comment]
Hi Jui-Fa, 

Thanks for your comment. I also set the "dataDir" in my conf file. I can see the log files in that dir before I close the client. But as soon as I close the client (i.e. the el_comandante.py), all the files are gone. It must be cleaned. 

So, in your case, do you have to set the [Transfer] parameters? Do you still see the files at the end?

Best,
Xin

**Comment by alphatsai** [comment]
Hi Xin,

“logfiles” doesn’t disappear after you close el_comandante, they are moved to your test folder which is under $dataDir.
[Transfer] parameters is for transferring to database, it doesn’t affect any the client or test.

Cheers,
Jui-Fa

Xin Shi <notifications@github.com<mailto:notifications@github.com>> 於 2015年2月6日 下午5:04 寫道：

Hi Jui-Fa,

Thanks for your comment. I also set the "dataDir" in my conf file. I can see the log files in that dir before I close the client. But as soon as I close the client (i.e. the el_comandante.py), all the files are gone. It must be cleaned.

So, in your case, do you have to set the [Transfer] parameters? Do you still see the files at the end?

Best,
Xin

**Comment by veloxid** [comment]
Hi 
Jui Fa is completly right: after beeing done the logfiles directory will be deleted because in each module test directory the logfiles directory is copied to...
So you should be able to set any storage path.
The [Transfer] parameteres are thought for scp the files to the DB.
