### ISSUE TITLE
Handling of pXar errors

### ISSUE THREAD

**Issue by piberger** [psi46/elComandante#4]
What happened to me today:
pXar failed in one test of the chain with a segmentation violation, but elComandante silently continued with the next test in the chain, without saving the error message of pxar. The only way the failure could be detected is, that the commander_*.log was incomplete (eg. "INFO: pXar: this is the end, my friend" is missing) and recorded data for following test was wrong because dacs haven't been saved. In case the test has only small influence on following tests, the failure could stay unnoticed unless all log files are checked.

It would be helpful to catch the pxar error and
- add it to error output of pxar to the logfile
- abort execution of test chain

or at least
- display a warning during and after the execution of the chain, that one test failed

**Comment by simonspa** [comment]
I would probably push it even further down the road, to pxar. Imo a software should _never_ segfault but return useful error codes in case something went wrong.

If you have the segfault backtrace somewhere it would be nice if you could open a pxar ticket for this.

**Comment by veloxid** [comment]
I agree that the error handling must be improved when running elComandante, but I agree with @simonspa that we should figure out what was wrong ... 
Could you give some more details?

**Comment by piberger** [comment]
The error in pxar has already been fixed in 8e4683a. It seems for like the segmentation violation was handled by a error handler of root.
Of course software _should_ never crash with not properly handled exceptions, but it might just happen and should be detected then.
Maybe these types of errors can be caught by redirecting the stderr to elComandante. It could also help to let elComandante automatically check if the last line of the log contains the "INFO: pXar: this is the end, my friend" to see if pxar finished normally or add some more machine friendly cross check to pxar which tells elComandante that the whole test was successful.
