### ISSUE TITLE
powercycle bug

### ISSUE THREAD

**Issue by xerxes1986** [psi46/elComandante#8]
The "powercycle" test inside elComandante has a bug where it will crash the program if it is run twice in a row. The code is _supposed_ to delete the powercycle testdir, but this "rmtree" command fails to actually remove the directory. Then when the next powercycle test is setup the "copytree" command fails with "Could not make directory: already exists" error and this causes the entire program to crash.

**Comment by piberger** [comment]
This seems to be a problem with NFS file system. rmtree recursively deletes the files in a directory, but when files are still open (current/temp/humidity logs are also written during cleanup), this will leave .nfs\* files in the directory. rmtree wrongly assumes that the directory is empty after deleting all the files that were present in the beginning (neglecting the new .nfs files) and fails.
I will fix this soon.
